version: '3'

volumes:
  policer-db:

services:
  db:
    image: mongo
    profiles:
      - policer
    volumes:
      - policer-db:/data/db
    ports:
      - 27017:27017

  api:
    image: ghcr.io/policer-io/api:v0.1.4-alpha.0
    profiles:
      - policer
    ports:
      - 5010:5000
    depends_on:
      - db
    environment:
      DB_URI: 'mongodb://${POLICER_DB_USER}:${POLICER_DB_PASS}@db:27017/${POLICER_DB_NAME}?authSource=admin'
      LOGGER_LEVEL: info
      PORT: 5000
      APP_API_KEY: ${APP_API_KEY}
      CORS_REGEX: '^http:\/\/localhost'
      OPS_ENV: local
      STAGE_DNS_NAME: localhost
    tty: true # makes the service logs colorful
    command: yarn start
